// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3bppekKz3g8uzqqJ2xtrKs
// Component: -bR8ejSXrj43
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import PriceCard from "../../PriceCard"; // plasmic-import: zAfM9xUtE6Fq/component
import { useScreenVariants as useScreenVariants_77ZxPqql0X83 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 77ZXPqql0x83/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 3bppekKz3g8uzqqJ2xtrKs/projectcss
import sty from "./PlasmicPriceSection.module.css"; // plasmic-import: -bR8ejSXrj43/css

createPlasmicElementProxy;

export const PlasmicPriceSection__VariantProps = new Array();

export const PlasmicPriceSection__ArgProps = new Array();

const $$ = {};

function PlasmicPriceSection__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_77ZxPqql0X83()
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__o2S9E)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__vxJne)}>
          <PriceCard
            borders={["flatLeft"]}
            className={classNames("__wab_instance", sty.priceCard__ogpKj)}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__nywSt)}>
          <div className={classNames(projectcss.all, sty.freeBox___5K9K)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {"We Recommended"}
            </div>
          </div>
          <PriceCard
            borders={["flatCenter"]}
            className={classNames("__wab_instance", sty.priceCard___9WfaR)}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___5Hd1Q)}>
          <PriceCard
            borders={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? ["flatRight"]
                : ["flatRight"]
            }
            className={classNames("__wab_instance", sty.priceCard__vDgFu)}
          />
        </div>
      </Stack__>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPriceSection__ArgProps,
          internalVariantPropNames: PlasmicPriceSection__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPriceSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPriceSection";
  } else {
    func.displayName = `PlasmicPriceSection.${nodeName}`;
  }
  return func;
}

export const PlasmicPriceSection = Object.assign(
  // Top-level PlasmicPriceSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicPriceSection
    internalVariantProps: PlasmicPriceSection__VariantProps,
    internalArgProps: PlasmicPriceSection__ArgProps
  }
);

export default PlasmicPriceSection;
/* prettier-ignore-end */
